version: '3.8'
services:
  api:
    depends_on:
      - db
    build: ./
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=jump
      - POSTGRES_PASS=password
      - POSTGRES_DB=postgres
    ports:
      - '8080:8080'
    links:
      - "db:database"
  db:
    build: ./database
    ports:
      - "5432:5432"